version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: /
    registries: '*'
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Oslo
    open-pull-requests-limit: 20
    groups:
      nav-packages:
          patterns:
            - "@navikt/*"
      react-deps:
        patterns:
          - "react*"
          - "@types/react*"
      dev-deps:
        patterns:
          - "*eslint*"
          - "typescript*"
          - "vite"
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "@navikt/*"
          - "react*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Oslo
