version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Oslo
    open-pull-requests-limit: 20
    groups:
      all-dependencies:
        patterns:
          - "*"
        applies-to: version-updates
          
          
      