apiVersion: "nais.io/v1alpha1"
kind: "Application"

metadata:
  name: burde-forstatt-frontend
  namespace: tilbake
  annotations:
    nais.io/run-as-group: "101"
    nais.io/run-as-user: "101"
  labels:
    team: tilbake
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /
    initialDelay: 10
    failureThreshold: 10
  readiness:
    path: /
    initialDelay: 10
    failureThreshold: 10
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi
      cpu: 25m
  filesFrom:
    - mountPath: /var/cache/nginx
      emptyDir:
        medium: Memory
    - mountPath: /var/run
      emptyDir:
        medium: Memory
  ingresses:
    - https://burde-forstatt.ansatt.dev.nav.no
