application:
  name: burde-forstatt

tilbakekreving:
  url: https://tilbakekreving-backend.intern.nav.no/api/behandling/v1

mq:
  host: "b27apvl220.preprod.local",
  port: 1413,
  channel: "Q1_FAMILIE_TILBAKE",
  queueManager: "MQLS02",
  queue: "QA.Q1_FAMILIE_TILBAKE.KRAVGRUNNLAG"
  enabled: true

local:
  mq:
    host: localhost
    port: 1414
    channel: DEV.APP.SVRCONN
    queuemanager: QM1
    queue: QA.Q1_FAMILIE_TILBAKE.KRAVGRUNNLAG
    enabled: true


